export interface IconEntry {
  filename: string;
  name: string;
  faction: 'ru' | 'us' | 'generic';
  category: string;
  path: string;
}

const factionMap: Record<string, 'ru' | 'us' | 'generic'> = {
  RU_: 'ru',
  US_: 'us',
  BLT_: 'generic',
  DLC2_: 'generic',
  ZMB_: 'generic',
  GENERIC_: 'generic',
};

const categoryMap: Record<string, string> = {
  HMG_KORD: 'Снаряжение',
  AGS_17: 'Снаряжение',
  SPG9: 'Снаряжение',
  PKP: 'Снаряжение',
  JAVELIN: 'Снаряжение',
  FLAMETHROWER: 'Снаряжение',
  TOW: 'Снаряжение',
  TANK: 'Танк',
  BMP: 'БМП',
  BMD: 'БМД',
  BTR: 'БТР',
  ABRAMS: 'Танк',
  BRADLEY: 'БМП',
  STRYKER: 'БТР',
  HUMVEE: 'БТР',
  JLTV: 'БТР',
  LAV: 'БТР',
  ACV: 'БТР',
  AMPV: 'БТР',
  M113: 'БТР',
  M2A2: 'БМП',
  M3A3: 'БМП',
  M1A1: 'Танк',
  M1A2: 'Танк',
  T90: 'Танк',
  T80: 'Танк',
  T72: 'Танк',
  T14: 'Танк',
  T15: 'БМП',
  T62: 'Танк',
  BMD2: 'БМД',
  BMD4: 'БМД',
  BTR80: 'БТР',
  BTR82: 'БТР',
  BTR90: 'БТР',
  BTRD: 'БТР',
  BTR_MDM: 'БТР',
  BTR97: 'БТР',
  KURGANETS: 'БМП',
  BOOMERANG: 'БТР',
  BUMERANG: 'БТР',
  TIGR: 'БТР',
  TYPHOON: 'БТР',
  PTS4: 'БТР',
  MTLS: 'БТР',
  MTLB: 'БТР',
  SPRUT: 'САУ',
  MSTA: 'Артиллерия',
  GIAZINT: 'Артиллерия',
  KOALITSIYA: 'Артиллерия',
  MALKA: 'Артиллерия',
  TYULPAN: 'Артиллерия',
  NONA: 'Артиллерия',
  GVOZDIKA: 'Артиллерия',
  AKACIYA: 'Артиллерия',
  DROK: 'Артиллерия',
  VENA: 'Артиллерия',
  KHRIZANTEMA: 'ПТРК',
  KORNET: 'ПТРК',
  KONKURS: 'ПТРК',
  METIS: 'ПТРК',
  FAGOT: 'ПТРК',
  RPG: 'ПТРК',

  STURM: 'ПТРК',
  KORD: 'ПВО',
  IGLA: 'ПВО',
  STRELA: 'ПВО',
  OSA: 'ПВО',
  TOR: 'ПВО',
  BUK: 'ПВО',
  S300: 'ПВО',
  S350: 'ПВО',
  S400: 'ПВО',
  PANTSIR: 'ПВО',
  TUNGUSKA: 'ПВО',
  SHILKA: 'ПВО',
  DERIVATSIYA: 'ПВО',
  PATRIOT: 'ПВО',
  AVENGER: 'ПВО',
  THAAD: 'ПВО',
  CRAM: 'ПВО',
  HIMARS: 'Артиллерия',
  M270: 'Артиллерия',
  M109: 'Артиллерия',
  MML: 'Артиллерия',
  BM_21: 'Артиллерия',
  BM_30: 'Артиллерия',
  URAGAN: 'Артиллерия',
  ISKANDER: 'Артиллерия',
  TOCHKA: 'Артиллерия',
  TOS: 'Артиллерия',
  TOSOCHKA: 'Артиллерия',
  KA52: 'Вертолёт',
  KA50: 'Вертолёт',
  KA29: 'Вертолёт',
  KA226: 'Вертолёт',
  KA60: 'Вертолёт',
  MI24: 'Вертолёт',
  MI28: 'Вертолёт',
  MI35: 'Вертолёт',
  MI8: 'Вертолёт',
  MI26: 'Вертолёт',
  MI38: 'Вертолёт',
  AH64: 'Вертолёт',
  AH1: 'Вертолёт',
  AH6: 'Вертолёт',
  UH60: 'Вертолёт',
  UH1: 'Вертолёт',
  CH47: 'Вертолёт',
  CH53: 'Вертолёт',
  MH60: 'Вертолёт',
  MH47: 'Вертолёт',
  SEAHAWK: 'Вертолёт',
  VENOM: 'Вертолёт',
  KIOWA: 'Вертолёт',
  RAH66: 'Вертолёт',
  SU25: 'Авиация',
  SU24: 'Авиация',
  SU27: 'Авиация',
  SU30: 'Авиация',
  SU33: 'Авиация',
  SU34: 'Авиация',
  SU35: 'Авиация',
  SU57: 'Авиация',
  MIG29: 'Авиация',
  MIG31: 'Авиация',
  TU160: 'Авиация',
  TU22: 'Авиация',
  TU95: 'Авиация',
  YAK130: 'Авиация',
  YAK38: 'Авиация',
  IL76: 'Авиация',
  AN72: 'Авиация',
  A10: 'Авиация',
  F15: 'Авиация',
  F16: 'Авиация',
  F22: 'Авиация',
  F35: 'Авиация',
  F14: 'Авиация',
  F117: 'Авиация',
  FA18: 'Авиация',
  AV8B: 'Авиация',
  C130: 'Авиация',
  C17: 'Авиация',
  B1B: 'Авиация',
  B2: 'Авиация',
  B52: 'Авиация',
  AC130: 'Авиация',
  E6: 'Авиация',
  EA6: 'Авиация',
  MQ: 'БПЛА',
  RQ: 'БПЛА',
  ORION: 'БПЛА',
  FORPOST: 'БПЛА',
  KORSAR: 'БПЛА',
  INFANTRY: 'Пехота',
  RIFLEMEN: 'Пехота',
  RECON: 'Разведка',
  SPECIAL: 'Спецназ',
  SPECNAZ: 'Спецназ',
  SPETSNAZ: 'Спецназ',
  VDV: 'ВДВ',
  PARATROOPERS: 'ВДВ',
  AIRBORNE: 'ВДВ',
  MARINES: 'Морпехи',
  RANGERS: 'Рейнджеры',
  SEALS: 'Спецназ',
  DELTA: 'Спецназ',
  SOAR: 'Спецназ',
  GREEN: 'Спецназ',
  SSO: 'Спецназ',
  FSB: 'Спецназ',
  GRU: 'Спецназ',
  VYMPEL: 'Спецназ',
  ALPHA: 'Спецназ',
  RAZVEDKA: 'Разведка',
  CAVALRY: 'Разведка',
  SCOUT: 'Разведка',
  SNIPER: 'Снайпер',
  MARKSMAN: 'Снайпер',
  ENGINEER: 'Инженеры',
  SAPERI: 'Инженеры',
  UR77: 'Инженеры',
  MICLIC: 'Инженеры',
  M1150: 'Инженеры',
  DOZER: 'Инженеры',
  PARARESCUE: 'Медицина',
  MEDICAL: 'Медицина',
  PILOT: 'Пилот',
  MOTOSTRELKI: 'Мотострелки',
  MECH: 'Механизированные',
};

export function mapIconFilename(filename: string): IconEntry {
  const withoutExt = filename.replace(/\.(png|svg|webp)$/i, '').replace(/-Label$/, '');
  let faction: IconEntry['faction'] = 'generic';
  for (const [prefix, f] of Object.entries(factionMap)) {
    if (withoutExt.startsWith(prefix)) { faction = f; break; }
  }

  let name = withoutExt.replace(/^(RU_|US_|BLT_|DLC2_|ZMB_|GENERIC_)/, '');
  name = name.replace(/_/g, ' ').replace(/\s+/g, ' ').trim();

  let category = 'Общее';
  const upperName = withoutExt.toUpperCase();
  for (const [key, cat] of Object.entries(categoryMap)) {
    if (upperName.includes(key)) { category = cat; break; }
  }

  return {
    filename,
    name,
    faction,
    category,
    path: `/icons/${filename}`,
  };
}

export function getAllIcons(): IconEntry[] {
  const iconNames = [
    "BALLOON-Label.png", "BALT_LEO2A7_TRAIN-Label.png", "BALT_LEO2A7-Label.png",
    "BLT_CV9035-Label.png", "BLT_EST_SCOUTS-Label.png", "BLT_GELEZINIS-Label.png",
    "BLT_JAGER-Label.png", "BLT_JALAVAE-Label.png", "BLT_MEHANIZETIE-Label.png",
    "BLT_PZH2000-Label.png", "BLT_RARDEN-Label.png", "BLT_RESERVISTS-Label.png",
    "BLT_SNIPER-Label.png", "BLT_SPIKE_SR-Label.png", "BLT_SPIKE-Label.png",
    "BLT_UNIMOG-Label.png", "BLT_VILKAS-Label.png", "BLT_XA180-Label.png",
    "GENERIC_INFANTRY-Label.png", "GENERIC_RECON-Label.png", "GENERIC_RIFLEMEN-Label.png",
    "GENERIC_SNIPER-Label.png", "OFFICER-Label.png", "PLACEHOLDER-Label.png",
    "VIP-Label.png", "supply-Label.png",
    "US_A10-Label.png", "US_ABRAMS-Label.png", "US_AH_1Z-Label.png",
    "US_AH64_APACHE-Label.png", "US_AH64_LONGBOW-Label.png",
    "US_BRADLEY_A2-Label.png", "US_BRADLEY_A3-Label.png",
    "US_CH47-Label.png", "US_F16_BLOCK52-Label.png", "US_F22-Label.png",
    "US_F35-Label.png", "US_HIMARS-Label.png", "US_HUMVEE-Label.png",
    "US_JAVELIN-Label.png", "US_JLTV-Label.png", "US_M1A2_SEPV3-Label.png",
    "US_M109_PALADIN-Label.png", "US_M2-Label.png", "US_PATRIOT_PAC3-Label.png",
    "US_RANGER-Label.png", "US_STRYKER_ICV-Label.png", "US_UH60-Label.png",
    "US_UH60M-Label.png", "US_MARINES-Label.png", "US_NAVY_SEALS-Label.png",
    "US_DELTA_FORCE-Label.png", "US_PARATROOPERS-Label.png",
    "RU_AGS_17-Label.png", "RU_BMD_2-Label.png", "RU_BMD_4-Label.png",
    "RU_BMP2-Label.png", "RU_BMP3-Label.png", "RU_BTR80-Label.png",
    "RU_BTR82-Label.png", "RU_BTR82_AT-Label.png", "RU_BTRD-Label.png",
    "RU_BTR_MDM-Label.png", "RU_IGLA-Label.png", "RU_KA52-Label.png",
    "RU_KONKURS-Label.png", "RU_KORNET-Label.png", "RU_METIS-Label.png",
    "RU_MI8_AMTSH-Label.png", "RU_MI24-Label.png", "RU_MI28N-Label.png",
    "RU_MSTA-Label.png", "RU_PANTSIR-Label.png", "RU_SHILKA-Label.png",
    "RU_SPRUT_SD-Label.png", "RU_T72B-Label.png", "RU_T80_BVM-Label.png",
    "RU_T90A-Label.png", "RU_T90M-Label.png", "RU_T14-Label.png",
    "RU_T15-Label.png", "RU_TOS-Label.png", "RU_TUNGUSKA-Label.png",
    "RU_URAGAN_1M-Label.png", "RU_VDV_PARA-Label.png", "RU_VDV_RAZVEDKA-Label.png",
    "RU_VDV_SNIPER-Label.png", "RU_MOTOSTRELKI-Label.png", "RU_BUK_M3-Label.png",
    "RU_S400-Label.png", "RU_TOR-Label.png", "RU_KURGANETS-Label.png",
    "RU_BTR90-Label.png", "RU_BTR97_KORD-Label.png", "RU_BMD2_KONKURS-Label.png",
    "RU_BMD2_KORNET-Label.png", "RU_PKP-Label.png", "RU_BLACK_BERET-Label.png",
    "RU_FLAMETHROWER-Label.png", "RU_HMG_KORD-Label.png", "RU_SNAIPERY_ASVK-Label.png",
    "RU_RPG29-Label.png", "RU_SPG9-Label.png", "RU_SPECNAZ_GRU-Label.png",
    "RU_SPECNAZ_VDV-Label.png", "RU_SSO-Label.png", "RU_PILOT-Label.png",
    "RU_TANK_CREW-Label.png", "RU_TYPHOON_VDV_KORD-Label.png",
    "RU_KAMAZ_6560-Label.png", "RU_URAL_4320-Label.png",
    "DLC2_CV9035_SPIKE-Label.png", "DLC2_LEO2A8-Label.png",
    "DLC2_PZH2000-label.png", "DLC2_UH60M-label.png",
    "DLC2_XA180-label.png", "DLC2_M2-label.png",
    "WOMAN_SNIPER-Label.png", "ZMB_CIVILIANS-Label.png", "ZMB_POLICE-Label.png",
  ];
  return iconNames.map(mapIconFilename);
}

export function getIconsByCategory(category: string): IconEntry[] {
  return getAllIcons().filter(i => i.category === category);
}

export function getCategories(): string[] {
  const cats = new Set(getAllIcons().map(i => i.category));
  return ['Все', ...Array.from(cats).sort()];
}
