import { ICON_FILENAMES } from './iconList';

export interface IconEntry {
  filename: string;
  name: string;
  faction: 'ru' | 'us' | 'generic';
  category: string;
  path: string;
}

const factionMap: Record<string, 'ru' | 'us' | 'generic'> = {
  RU_: 'ru',
  US_: 'us',
  BLT_: 'generic',
  DLC2_: 'generic',
  ZMB_: 'generic',
  GENERIC_: 'generic',
};

const categoryMap: Record<string, string> = {
  // Equipment (Снаряжение) — specific keys first to avoid false matches
  HMG_KORD: 'Снаряжение',
  AGS_17: 'Снаряжение',
  AGS_30: 'Снаряжение',
  AGS_40: 'Снаряжение',
  AGS_AK: 'Снаряжение',
  SPG9: 'Снаряжение',
  PKP: 'Снаряжение',
  JAVELIN: 'Снаряжение',
  FLAMETHROWER: 'Снаряжение',
  TOW: 'Снаряжение',
  GMG: 'Снаряжение',
  GROM: 'Снаряжение',
  MILAN: 'Снаряжение',
  PIORUN: 'Снаряжение',
  RBS70: 'Снаряжение',
  SMAW: 'Снаряжение',
  DRAGON: 'Снаряжение',
  MK19: 'Снаряжение',
  STINGER: 'Снаряжение',
  SPIKE: 'Снаряжение',
  IRIST: 'Снаряжение',
  NASAMS: 'ПВО',
  ZU_23: 'Снаряжение',
  NSV: 'Снаряжение',
  ALBATROS: 'Авиация',
  SPARTAN: 'Снаряжение',
  KASP: 'Снаряжение',
  M2_GMG: 'Снаряжение',
  TGB_RBS: 'Снаряжение',
  TGB_1111: 'Снаряжение',
  UNIMOG: 'БТР',
  // Vehicles
  TANK: 'Танк',
  BMP: 'БМП',
  BMD: 'БМД',
  BTR: 'БТР',
  ABRAMS: 'Танк',
  BRADLEY: 'БМП',
  STRYKER: 'БТР',
  HUMVEE: 'БТР',
  JLTV: 'БТР',
  LAV: 'БТР',
  ACV: 'БТР',
  AMPV: 'БТР',
  M113: 'БТР',
  M2A2: 'БМП',
  M3A3: 'БМП',
  M1A1: 'Танк',
  M1A2: 'Танк',
  T90: 'Танк',
  T80: 'Танк',
  T72: 'Танк',
  T14: 'Танк',
  T15: 'БМП',
  T62: 'Танк',
  BMD2: 'БМД',
  BMD4: 'БМД',
  BTR80: 'БТР',
  BTR82: 'БТР',
  BTR90: 'БТР',
  BTRD: 'БТР',
  BTR_MDM: 'БТР',
  BTR97: 'БТР',
  KURGANETS: 'БМП',
  BOOMERANG: 'БТР',
  BUMERANG: 'БТР',
  TIGR: 'БТР',
  TYPHOON: 'БТР',
  PTS4: 'БТР',
  MTLS: 'БТР',
  MTLB: 'БТР',
  SPRUT: 'САУ',
  MSTA: 'Артиллерия',
  GIAZINT: 'Артиллерия',
  KOALITSIYA: 'Артиллерия',
  MALKA: 'Артиллерия',
  TYULPAN: 'Артиллерия',
  NONA: 'Артиллерия',
  GVOZDIKA: 'Артиллерия',
  AKACIYA: 'Артиллерия',
  DROK: 'Артиллерия',
  VENA: 'Артиллерия',
  KHRIZANTEMA: 'ПТРК',
  KORNET: 'ПТРК',
  KONKURS: 'ПТРК',
  METIS: 'ПТРК',
  FAGOT: 'ПТРК',
  RPG: 'ПТРК',
  STURM: 'ПТРК',
  KORD: 'ПВО',
  IGLA: 'ПВО',
  STRELA: 'ПВО',
  OSA: 'ПВО',
  TOR: 'ПВО',
  BUK: 'ПВО',
  S300: 'ПВО',
  S350: 'ПВО',
  S400: 'ПВО',
  PANTSIR: 'ПВО',
  TUNGUSKA: 'ПВО',
  SHILKA: 'ПВО',
  DERIVATSIYA: 'ПВО',
  PATRIOT: 'ПВО',
  AVENGER: 'ПВО',
  THAAD: 'ПВО',
  CRAM: 'ПВО',
  HIMARS: 'Артиллерия',
  M270: 'Артиллерия',
  M109: 'Артиллерия',
  MML: 'Артиллерия',
  BM_21: 'Артиллерия',
  BM_30: 'Артиллерия',
  URAGAN: 'Артиллерия',
  ISKANDER: 'Артиллерия',
  TOCHKA: 'Артиллерия',
  TOS: 'Артиллерия',
  TOSOCHKA: 'Артиллерия',
  KA52: 'Вертолёт',
  KA50: 'Вертолёт',
  KA29: 'Вертолёт',
  KA226: 'Вертолёт',
  KA60: 'Вертолёт',
  MI24: 'Вертолёт',
  MI28: 'Вертолёт',
  MI35: 'Вертолёт',
  MI8: 'Вертолёт',
  MI26: 'Вертолёт',
  MI38: 'Вертолёт',
  AH64: 'Вертолёт',
  AH1: 'Вертолёт',
  AH6: 'Вертолёт',
  UH60: 'Вертолёт',
  UH1: 'Вертолёт',
  CH47: 'Вертолёт',
  CH53: 'Вертолёт',
  MH60: 'Вертолёт',
  MH47: 'Вертолёт',
  SEAHAWK: 'Вертолёт',
  VENOM: 'Вертолёт',
  KIOWA: 'Вертолёт',
  RAH66: 'Вертолёт',
  SU25: 'Авиация',
  SU24: 'Авиация',
  SU27: 'Авиация',
  SU30: 'Авиация',
  SU33: 'Авиация',
  SU34: 'Авиация',
  SU35: 'Авиация',
  SU57: 'Авиация',
  MIG29: 'Авиация',
  MIG31: 'Авиация',
  TU160: 'Авиация',
  TU22: 'Авиация',
  TU95: 'Авиация',
  YAK130: 'Авиация',
  YAK38: 'Авиация',
  IL76: 'Авиация',
  AN72: 'Авиация',
  A10: 'Авиация',
  F15: 'Авиация',
  F16: 'Авиация',
  F22: 'Авиация',
  F35: 'Авиация',
  F14: 'Авиация',
  F117: 'Авиация',
  FA18: 'Авиация',
  AV8B: 'Авиация',
  C130: 'Авиация',
  C17: 'Авиация',
  B1B: 'Авиация',
  B2: 'Авиация',
  B52: 'Авиация',
  AC130: 'Авиация',
  E6: 'Авиация',
  EA6: 'Авиация',
  L39: 'Авиация',
  MQ: 'БПЛА',
  RQ: 'БПЛА',
  ORION: 'БПЛА',
  FORPOST: 'БПЛА',
  KORSAR: 'БПЛА',
  INFANTRY: 'Пехота',
  RIFLEMEN: 'Пехота',
  RECON: 'Разведка',
  SPECIAL: 'Спецназ',
  SPECNAZ: 'Спецназ',
  SPETSNAZ: 'Спецназ',
  VDV: 'ВДВ',
  PARATROOPERS: 'ВДВ',
  AIRBORNE: 'ВДВ',
  MARINES: 'Морпехи',
  RANGERS: 'Рейнджеры',
  SEALS: 'Спецназ',
  DELTA: 'Спецназ',
  SOAR: 'Спецназ',
  GREEN: 'Спецназ',
  SSO: 'Спецназ',
  FSB: 'Спецназ',
  GRU: 'Спецназ',
  VYMPEL: 'Спецназ',
  ALPHA: 'Спецназ',
  RAZVEDKA: 'Разведка',
  CAVALRY: 'Разведка',
  SCOUT: 'Разведка',
  SNIPER: 'Снайпер',
  MARKSMAN: 'Снайпер',
  ENGINEER: 'Инженеры',
  SAPERI: 'Инженеры',
  UR77: 'Инженеры',
  MICLIC: 'Инженеры',
  M1150: 'Инженеры',
  DOZER: 'Инженеры',
  PARARESCUE: 'Медицина',
  MEDICAL: 'Медицина',
  PILOT: 'Пилот',
  MOTOSTRELKI: 'Мотострелки',
  MECH: 'Механизированные',
};

export function mapIconFilename(filename: string): IconEntry {
  const withoutExt = filename.replace(/\.(png|svg|webp)$/i, '').replace(/-Label$/i, '');
  let faction: IconEntry['faction'] = 'generic';
  for (const [prefix, f] of Object.entries(factionMap)) {
    if (withoutExt.startsWith(prefix)) { faction = f; break; }
  }

  let name = withoutExt.replace(/^(RU_|US_|BLT_|DLC2_|ZMB_|GENERIC_)/, '');
  name = name.replace(/_/g, ' ').replace(/\s+/g, ' ').trim();

  let category = 'Общее';
  const upperName = withoutExt.toUpperCase();
  for (const [key, cat] of Object.entries(categoryMap)) {
    if (upperName.includes(key)) { category = cat; break; }
  }

  return {
    filename,
    name,
    faction,
    category,
    path: `/icons/${filename}`,
  };
}

export function getAllIcons(): IconEntry[] {
  return ICON_FILENAMES.map(mapIconFilename);
}

export function getIconsByCategory(category: string): IconEntry[] {
  return getAllIcons().filter(i => i.category === category);
}

export function getCategories(): string[] {
  const cats = new Set(getAllIcons().map(i => i.category));
  return ['Все', ...Array.from(cats).sort()];
}
